[package]
name = "bitmap_type_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
serde = { version = "1.0", features = [] }
serde_json = "1.0"
serde_derive = { version = "1.0", features = [] }
